import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";


import type { Metadata } from "next";
import { Nunito_Sans, Oxygen } from "next/font/google";

import { cn } from "@/lib/utils";

const fontSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "700"],
  display: "swap",
});

const fontHeading = Oxygen({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["300", "400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={cn(fontSans.variable, fontHeading.variable)}>
        <body
          className={cn(
            "min-h-screen font-sans antialiased",
          )}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>

  );
}
